/*
©2022 Pivotree | All rights reserved
*/
// auth
export const TOGGLE_USER_LOGIN = "TOGGLE_USER_LOGIN";
export const SAVE_SOCKET = "SAVE_SOCKET";
export const CURRENT_SELECTED_PERSON = "CURRENT_SELECTED_PERSON";
export const SAVE_CONTACTS = "SAVE_CONTACTS";
export const SAVE_GROUPS = "SAVE_GROUPS";
export const SAVE_PER_GROUP_USERS = "SAVE_PER_GROUP_USERS";
export const TOGGLE_USER_FAILED = "TOGGLE_USER_FAILED";
export const RESET_STORE = "RESET_STORE";

//common
export const SAVE_MENU_STATE = "SAVE_MENU_STATE";
export const SET_FIELDS_JSON = "SET_FIELDS_JSON";
export const SET_FIELDS_STATE = "SET_FIELDS_STATE";
export const CACHE_MEDIA_DATA = "CACHE_MEDIA_DATA";
export const SET_STEPPER_STATE = "SET_STEPPER_STATE";
export const TOGGLE_SNACKBAR = "TOGGLE_SNACKBAR";
export const TOGGLE_SESSION_PROMPT = "TOGGLE_SESSION_PROMPT";
export const SAVE_LOGGED_IN_DATA = "SAVE_LOGGED_IN_DATA";
export const COMMON_ACTION = "COMMON_ACTION";
export const COMMON_ACTION_SUCCESS = "COMMON_ACTION_SUCCESS";
export const COMMON_ACTION_FAILED = "COMMON_ACTION_FAILED";
